//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazUsuario.Referencia {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ExtendedPropertiesDictionary", Namespace="http://schemas.datacontract.org/2004/07/Entidades", ItemName="ExtendedProperties", KeyName="Name", ValueName="ExtendedProperty")]
    [System.SerializableAttribute()]
    public class ExtendedPropertiesDictionary : System.Collections.Generic.Dictionary<string, object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectsAddedToCollectionProperties", Namespace="http://schemas.datacontract.org/2004/07/Entidades", ItemName="AddedObjectsForProperty", KeyName="CollectionPropertyName", ValueName="AddedObjects")]
    [System.SerializableAttribute()]
    public class ObjectsAddedToCollectionProperties : System.Collections.Generic.Dictionary<string, InterfazUsuario.Referencia.ObjectList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectList", Namespace="http://schemas.datacontract.org/2004/07/Entidades", ItemName="ObjectValue")]
    [System.SerializableAttribute()]
    public class ObjectList : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectsRemovedFromCollectionProperties", Namespace="http://schemas.datacontract.org/2004/07/Entidades", ItemName="DeletedObjectsForProperty", KeyName="CollectionPropertyName", ValueName="DeletedObjects")]
    [System.SerializableAttribute()]
    public class ObjectsRemovedFromCollectionProperties : System.Collections.Generic.Dictionary<string, InterfazUsuario.Referencia.ObjectList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OriginalValuesDictionary", Namespace="http://schemas.datacontract.org/2004/07/Entidades", ItemName="OriginalValues", KeyName="Name", ValueName="OriginalValue")]
    [System.SerializableAttribute()]
    public class OriginalValuesDictionary : System.Collections.Generic.Dictionary<string, object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TrackableCollectionOfCiudadrzoQK7bR", Namespace="http://schemas.datacontract.org/2004/07/Entidades", ItemName="Ciudad")]
    [System.SerializableAttribute()]
    public class TrackableCollectionOfCiudadrzoQK7bR : System.Collections.Generic.List<Entidades.Ciudad> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Referencia.IEfDemo")]
    public interface IEfDemo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEfDemo/ObtenerPaises", ReplyAction="http://tempuri.org/IEfDemo/ObtenerPaisesResponse")]
        System.Collections.Generic.List<Entidades.Pais> ObtenerPaises();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEfDemo/Modificar", ReplyAction="http://tempuri.org/IEfDemo/ModificarResponse")]
        int Modificar(Entidades.Pais pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEfDemo/ObtenerPaisPorId", ReplyAction="http://tempuri.org/IEfDemo/ObtenerPaisPorIdResponse")]
        Entidades.Pais ObtenerPaisPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEfDemo/InsertarPais", ReplyAction="http://tempuri.org/IEfDemo/InsertarPaisResponse")]
        int InsertarPais(Entidades.Pais pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEfDemo/ModificarPaisPorId", ReplyAction="http://tempuri.org/IEfDemo/ModificarPaisPorIdResponse")]
        int ModificarPaisPorId(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEfDemoChannel : InterfazUsuario.Referencia.IEfDemo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EfDemoClient : System.ServiceModel.ClientBase<InterfazUsuario.Referencia.IEfDemo>, InterfazUsuario.Referencia.IEfDemo {
        
        public EfDemoClient() {
        }
        
        public EfDemoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EfDemoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EfDemoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EfDemoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.Pais> ObtenerPaises() {
            return base.Channel.ObtenerPaises();
        }
        
        public int Modificar(Entidades.Pais pais) {
            return base.Channel.Modificar(pais);
        }
        
        public Entidades.Pais ObtenerPaisPorId(int id) {
            return base.Channel.ObtenerPaisPorId(id);
        }
        
        public int InsertarPais(Entidades.Pais pais) {
            return base.Channel.InsertarPais(pais);
        }
        
        public int ModificarPaisPorId(int id) {
            return base.Channel.ModificarPaisPorId(id);
        }
    }
}
